/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

/**
 *
 * @author Juande
 */
public class FrameAgregar extends javax.swing.JFrame {

    /**
     * Creates new form FrameAgregar
     */
    public FrameAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSuelo = new javax.swing.JButton();
        txtSuelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPared = new javax.swing.JTextField();
        btnPared = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGoomba = new javax.swing.JTextField();
        btnGoomba = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnTortuga = new javax.swing.JButton();
        txtTortuga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnMoneda = new javax.swing.JButton();
        txtMoneda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVida = new javax.swing.JTextField();
        btnHongo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMario = new javax.swing.JTextField();
        btnMario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCastillo = new javax.swing.JTextField();
        btnCastillo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuelo.setText("Agregar Suelo");
        getContentPane().add(btnSuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        getContentPane().add(txtSuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Suelo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pared.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 40, -1));
        getContentPane().add(txtPared, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, -1));

        btnPared.setText("Agregar Pared");
        getContentPane().add(btnPared, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Goomba.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 40, -1));
        getContentPane().add(txtGoomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 120, -1));

        btnGoomba.setText("Agregar Goomba");
        getContentPane().add(btnGoomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Koopa.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 40, -1));

        btnTortuga.setText("Agregar Koopa");
        getContentPane().add(btnTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));
        getContentPane().add(txtTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moneda.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 40, -1));

        btnMoneda.setText("Agregar Moneda");
        getContentPane().add(btnMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));
        getContentPane().add(txtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HongoVida.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 40, -1));

        txtVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, -1));

        btnHongo.setText("Agregar Hongo");
        getContentPane().add(btnHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mario.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 40, -1));
        getContentPane().add(txtMario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 110, -1));

        btnMario.setText("Agregar Mario");
        getContentPane().add(btnMario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Castillo.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 40, -1));
        getContentPane().add(txtCastillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 120, -1));

        btnCastillo.setText("Agregar Castillo");
        getContentPane().add(btnCastillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSeleccion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 868, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCastillo;
    private javax.swing.JButton btnGoomba;
    private javax.swing.JButton btnHongo;
    private javax.swing.JButton btnMario;
    private javax.swing.JButton btnMoneda;
    private javax.swing.JButton btnPared;
    private javax.swing.JButton btnSuelo;
    private javax.swing.JButton btnTortuga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCastillo;
    private javax.swing.JTextField txtGoomba;
    private javax.swing.JTextField txtMario;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtPared;
    private javax.swing.JTextField txtSuelo;
    private javax.swing.JTextField txtTortuga;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables
}
