/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Estructuras.ListaObjetos;
import Estructuras.MatrizOrtogonal;
import Estructuras.NodoObjeto;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Juande
 */
public class InterfazAgregar extends javax.swing.JFrame {

    //public static ListaObjetos ListaObj = new ListaObjetos();
    //public static MatrizOrtogonal tablero;
    public int ID = 1;
    /**
     * Creates new form InterfazAgregar
     */
    public InterfazAgregar() {
        this.setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSuelo = new javax.swing.JButton();
        txtSuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPared = new javax.swing.JTextField();
        btnPared = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTortuga = new javax.swing.JTextField();
        btnTortuga = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMario = new javax.swing.JTextField();
        btnMario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtGoomba = new javax.swing.JTextField();
        btnGoomba = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        btnMoneda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtHongo = new javax.swing.JTextField();
        btnHongo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCastillo = new javax.swing.JTextField();
        btnCastillo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 622));
        setMinimumSize(new java.awt.Dimension(800, 622));
        setPreferredSize(new java.awt.Dimension(840, 622));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuelo.setText("Agregar Suelo");
        btnSuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueloActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));
        getContentPane().add(txtSuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Suelo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 40, 40));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pared.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 40, -1));
        getContentPane().add(txtPared, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, -1));

        btnPared.setText("Agregar Pared");
        btnPared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParedActionPerformed(evt);
            }
        });
        getContentPane().add(btnPared, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Koopa.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 40, -1));
        getContentPane().add(txtTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, -1));

        btnTortuga.setText("Agregar Koopa");
        btnTortuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTortugaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mario.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 40, -1));
        getContentPane().add(txtMario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 80, -1));

        btnMario.setText("Agregar Mario");
        btnMario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Goomba.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 40, -1));
        getContentPane().add(txtGoomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 90, -1));

        btnGoomba.setText("Agregar Goomba");
        btnGoomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoombaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moneda.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 40, -1));
        getContentPane().add(txtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 90, -1));

        btnMoneda.setText("Agregar Moneda");
        btnMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HongoVida.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 40, -1));
        getContentPane().add(txtHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 90, -1));

        btnHongo.setText("Agregar Hongo");
        btnHongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHongoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/castillo.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 40, -1));
        getContentPane().add(txtCastillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, -1));

        btnCastillo.setText("Agregar Castillo");
        btnCastillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCastilloActionPerformed(evt);
            }
        });
        getContentPane().add(btnCastillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jButton1.setText("Confirmar->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSeleccion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 622));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 622));
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 622));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueloActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtSuelo.getText(), "Suelo", jLabel2.getIcon());
        ID++;
        txtSuelo.setText(null);
    }//GEN-LAST:event_btnSueloActionPerformed

    private void btnParedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParedActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtPared.getText(), "Pared", jLabel3.getIcon());
        ID++;
        txtPared.setText(null);
    }//GEN-LAST:event_btnParedActionPerformed

    private void btnTortugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTortugaActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtTortuga.getText(), "Koopa", jLabel4.getIcon());
        ID++;
        txtTortuga.setText(null);
    }//GEN-LAST:event_btnTortugaActionPerformed

    private void btnMarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarioActionPerformed
        // TODO add your handling code here:
        if(InterfazPrincipal.ListaObj.getCabeza() == null){
            AgregarObjeto(ID,txtMario.getText(), "Mario", jLabel5.getIcon());
            ID++;
            txtMario.setText(null);
        }else{
            NodoObjeto verificar;
            Boolean ver = false;
            Boolean aux;
            for(verificar = InterfazPrincipal.ListaObj.getCabeza(); verificar != null; verificar = verificar.getSiguiente()){
                if(verificar.getTipo().equals("Mario")){
                    
                    ver = true;
                    aux= ver;
                    break;
                }else{
                    ver = false;
                    aux = ver;
                }
            }
            if(ver == false){
                AgregarObjeto(ID,txtMario.getText(), "Mario", jLabel5.getIcon());
                ID++;
                txtMario.setText(null);
            }else{
                JOptionPane.showMessageDialog(null, "Ya existe un mario en la lista de objetos");
            }
        }               
    }//GEN-LAST:event_btnMarioActionPerformed

    private void btnGoombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoombaActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtGoomba.getText(), "Goomba", jLabel6.getIcon());
        ID++;
        txtGoomba.setText(null);
    }//GEN-LAST:event_btnGoombaActionPerformed

    
    private void btnHongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHongoActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtHongo.getText(), "Hongo", jLabel8.getIcon());
        ID++;
        txtHongo.setText(null);
    }//GEN-LAST:event_btnHongoActionPerformed

    private void btnMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonedaActionPerformed
        // TODO add your handling code here:
        AgregarObjeto(ID,txtMoneda.getText(), "Moneda", jLabel7.getIcon());
        ID++;
        txtMoneda.setText(null);
    }//GEN-LAST:event_btnMonedaActionPerformed

    private void btnCastilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCastilloActionPerformed
        // TODO add your handling code here:
        if(InterfazPrincipal.ListaObj.getCabeza() == null){
            AgregarObjeto(ID,txtCastillo.getText(), "Castillo",  jLabel9.getIcon());
            ID++;
            txtCastillo.setText(null);
        }else{
            NodoObjeto verificar;
            Boolean ver = false;
            Boolean aux;
            for(verificar = InterfazPrincipal.ListaObj.getCabeza(); verificar != null; verificar = verificar.getSiguiente()){
                if(verificar.getTipo().equals("Castillo")){
                    
                    ver = true;
                    aux= ver;
                    break;
                }else{
                    ver = false;
                    aux = ver;
                }
            }
            if(ver == false){
                AgregarObjeto(ID,txtCastillo.getText(), "Castillo",  jLabel9.getIcon());
                ID++;
                txtCastillo.setText(null);
            }else{
                JOptionPane.showMessageDialog(null, "Ya existe un castillo en la lista de objetos");
            }
        }
        
    }//GEN-LAST:event_btnCastilloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal.ListaObj.Visualizar();
        /*MatrizOrtogonal tablero = new MatrizOrtogonal();*/
        
        this.setVisible(false);
        ConfirmarObjetos conf = new ConfirmarObjetos();
        conf.setVisible(true);
        //tablero.Visualizar();
        //tablero.ImprimirMatriz();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    //Metodo para insertar un objeto en la lista
    public void AgregarObjeto(int ID,String nombre, String tipo, Icon imagen){
        NodoObjeto Objeto = new NodoObjeto(ID,nombre, tipo, imagen);
        InterfazPrincipal.ListaObj.InsertarObjeto(Objeto,ID, nombre, tipo, imagen);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCastillo;
    private javax.swing.JButton btnGoomba;
    private javax.swing.JButton btnHongo;
    private javax.swing.JButton btnMario;
    private javax.swing.JButton btnMoneda;
    private javax.swing.JButton btnPared;
    private javax.swing.JButton btnSuelo;
    private javax.swing.JButton btnTortuga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCastillo;
    private javax.swing.JTextField txtGoomba;
    private javax.swing.JTextField txtHongo;
    private javax.swing.JTextField txtMario;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtPared;
    private javax.swing.JTextField txtSuelo;
    private javax.swing.JTextField txtTortuga;
    // End of variables declaration//GEN-END:variables
}
