/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Estructuras.ListaObjetos;
import Estructuras.MatrizOrtogonal;
import Estructuras.NodoObjeto;
import Estructuras.NodoOrtogonal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.TransferHandler;

/**
 *
 * @author Juande
 */
public class Tablero extends javax.swing.JFrame {

    Graficadora grafica = new Graficadora();
    int IdObj;
    /**
     * Creates new form Tablero
     */
    //public JLabel imagen;
    public Tablero() {
        initComponents();
        //muestra objetos en el cuadrito
        MostrarObjeto();
        //pinta los nodos de la matriz
        PintarMatriz();        
        setLocationRelativeTo(null);
        jLabel1.setTransferHandler(new TransferHandler("icon"));
        
        //imagen.setTransferHandler(new TransferHandler("icon"));
    }
    //Metodo para mostrar la imagen del objeto en el label
    public void MostrarObjeto(){
        jLabel1.removeAll();
        if(InterfazPrincipal.ListaPila == true){
            if(InterfazPrincipal.pila.getCabeza() == null){
            jLabel1.setText("Vacio");
            }else{
                NodoObjeto aux = InterfazPrincipal.pila.getCabeza();
                this.jLabel1.setText(Integer.toString(aux.getID()));
                this.jLabel1.setIcon(aux.getImagen());
            }
        }else{
            if(InterfazPrincipal.ListaObj.getCabeza() == null){
            jLabel1.setText("Vacio");
            }else{
                NodoObjeto aux = InterfazPrincipal.ListaObj.getCabeza();
                this.jLabel1.setText(Integer.toString(aux.getID()));
                this.jLabel1.setIcon(aux.getImagen());
            }
        }
    }
    //Metodo para pintar la matriz
    public void PintarMatriz(/*MatrizOrtogonal Ortogonal*/){
        jPanel1.removeAll();
        ImageIcon nuevoicon = new ImageIcon(getClass().getResource("/Imagenes/Cielo1.png"));
         NodoOrtogonal aux1;
         NodoOrtogonal aux2;
         NodoOrtogonal aux3;
         int x=0;
         int y=0;
         //Imprime desde la fila ultima hasta la primera
        aux1 = InterfazPrincipal.tablero.getRaiz();
        while(aux1.getArriba() != null){
             aux1 = aux1.getArriba();
        }
        for(aux2 = aux1; aux2 != null ; aux2 = aux2.getAbajo()){
            aux3 = aux2;
            y++;
            while(aux3 != null){
                x++;
                aux3.imagen = new JButton();
                aux3.imagen.setBounds(40*x, 40*y, 39, 39);  
                if(this.jLabel1.getText().equals("Vacio")){
                    this.remove(jLabel1);
                }else{
                    aux3.Click(this,Integer.parseInt(this.jLabel1.getText()));
                }
                
                if(aux3.getObjeto() == null){
                    aux3.imagen.setIcon(nuevoicon);
                }else{
                    aux3.imagen.setIcon(aux3.getObjeto().getImagen());
                }               
                //jLabel1.removeAll();
                MostrarObjeto();
                jPanel1.revalidate();
                jPanel1.repaint();
                jPanel1.add(aux3.imagen);               
                aux3 = aux3.getSiguiente();              
            }
            x=0;           
        }               
        //Imprime de la primera a la ultima fila
        /*for(aux1 = cabeza; aux1 != null; aux1 = aux1.getArriba()){
             aux2 = aux1;
             y++;
             while(aux2 != null){
                 x++;
                 System.out.println(aux2.getPosx()+","+aux2.getPosy());
                 imagen = new JLabel();
                 //imagen.setIcon(nuevoicon);
                 imagen.setText("("+aux2.getPosx()+","+aux2.getPosy()+")");
                 imagen.setBounds((35*x),(35*y), 34, 34);
                 panel.add(imagen);
                 aux2 = aux2.getSiguiente();
             }
             x=0;
         }*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(4000, 4000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4000, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Objetos para Utilizar:");

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insertar Columna");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Insertar Fila");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Graficar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(71, 71, 71)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Boton para insertr columna
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal.tablero.InsertarColumna();
        jPanel1.removeAll();
        PintarMatriz();
        jPanel1.revalidate();
        jPanel1.repaint();
        
    }//GEN-LAST:event_jButton2ActionPerformed
    //Boton para insertar fila
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal.tablero.InsertarFila();
        jPanel1.removeAll();
        PintarMatriz();
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            grafica.dibujar_personajes(InterfazPrincipal.ListaObj, "Objetos");
            JOptionPane.showMessageDialog(rootPane, "Se creo las graficas de Objetos");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear la grafica de personajes");
        }
        try {
            grafica.GraficarMatriz(InterfazPrincipal.tablero, "Matriz");
            JOptionPane.showMessageDialog(rootPane, "Se creo las grafica de la matriz");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear la grafica de la matriz");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        /*if(InterfazPrincipal.ListaObj.getCabeza() == null){
            jLabel1.setIcon(null);
            jLabel1.setText(null);
            JOptionPane.showMessageDialog(null, "Ya no hay objetos en la lista");
        }else{
            JComponent comp = (JComponent) evt.getSource();
            TransferHandler handler = comp.getTransferHandler();
            handler.exportAsDrag(comp, evt, TransferHandler.COPY);            
            MostrarObjeto();
            InterfazPrincipal.ListaObj.Eliminar(Integer.parseInt(jLabel1.getText()));
            jLabel1.revalidate();
            jLabel1.repaint();
        }
        */     
    }//GEN-LAST:event_jLabel1MousePressed

    
    
    
    
    
    
    
    
    
//este no funciona
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_jLabel1MouseClicked
//NO FUNCIONA
    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(InterfazPrincipal.ListaPila == true){
            if(InterfazPrincipal.pila.getCabeza() != null){
                this.setVisible(false);
                Juego nuevo = new Juego();
            }else{
                JOptionPane.showMessageDialog(null, "Aun le quedan objetos por usar");
            }
        }else{
            if(InterfazPrincipal.ListaObj.getCabeza() != null){
                this.setVisible(false);
                Juego nuevo = new Juego();
            }else{
                JOptionPane.showMessageDialog(null, "Aun le quedan objetos por usar");
            }
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
